### ISSUE TITLE
Page /tournois

### ISSUE THREAD

**Issue by AntoninLoubiere** [AntoninLoubiere/hanamikoji-site#30]
Affiche la liste des tournois. Un bouton tout en haut permet d'accéder à la page /tournois/prochain (cf #31).

Sur chaque ligne, on voit la 
 - date de lancement du tournoi
 - le statut (EN_ATTENTE, LANCEMENT_PROGRAMMÉ, EN_COURS, FINI (ERREUR ?))
 - le champion qui a gagné
 - un bouton pour accéder au détail /tournois/<id>
 - *le nombre de matchs joués ?*
 - _le nombre de champions qui participent ?_

**Comment by Triw-12** [comment]
Le statut EN ATTENTE est-il nécessaire ? (je laisse le ERREUR au cas où)
Il me semble logique que quand on programme un tournoi, on indique forcément une date donc il n'est jamais en attente

**Comment by AntoninLoubiere** [comment]
L'objectif était de laisser un état où le lancement n'est pas automatique, par exemple si on prévoit un tournoi pour plus tard mais on ne sait pas si tout le monde sera prêt à temps pouvoir le décaler sans craindre d'arriver trop tard. Après je sais pas si c'est vraiment utile.

**Comment by Triw-12** [comment]
Réglé avec 4bbb02d et b81a6b1
