### ISSUE TITLE
Page /tournois/prochain

### ISSUE THREAD

**Issue by AntoninLoubiere** [AntoninLoubiere/hanamikoji-site#31]
Une page qui permet de définir ses champions qui participeront.
Il faut rajouter un attribut aux champions qui indiquent la date à laquelle ils ont été sélectionné pour le match ou NULL.
Quand un champion termine sa compilation / est ajouté ?, on désélectionne tous les champions (mettre NULL) et on ajoute le champion. Pour éviter des trucs bizarre, on désélectionne seulement les champions qui ont été sélectionné avant la date d'ajout du champion.

Tout en haut une boîte de choix permet de choisir et de sélectionner des champions (sans enlever)
On a une liste ordonnée qui affiche les champions sélectionnés :

1. Champion 1
2. Champion 2
3. Champion 3

Sur chaque ligne on peut soit désélectionner le champion soit le resélectionner (pour le remettre en tête de liste et ordonner sa liste). Chaque tournois indiqueras le nombre maximum de champion par personne autorisé (lors des tournois intermédiaires, on peut imaginer que on lance des tournois avec 2/3 champions par personne).

Tout en haut, afficher les informations du prochain tournois nombre maximum de champions, date de lancement, statut : EN_ATTENTE / LANCEMENT_PROGRAMMÉ. Sur la liste des champions sélectionner, griser les lignes qui dépassent le nombre de champions autorisé.

En bas / sur un autre page
Si l’utilisateur possède la permission tournois.choice_champions (ou alors plus simple, seulement les admin ?)
Il peut voir les champions pour chaque joueur et en ajouter au besoin ?

**Comment by Triw-12** [comment]
Je t'avoue que j'ai pas très bien compris, il me faudrait un petit croquis...
Je vais essayer d'en faire un

**Comment by Triw-12** [comment]
![WhatsApp Image 2023-07-29 à 20 49 57 2](https://github.com/AntoninLoubiere/hanamikoji-site/assets/61625831/e856b2ae-483e-4d49-b2a4-fb19d9015b27)

Là on peut tous les choisir d'un coup mais la vérification que le nombre n'est pas dépassé se fait seulement quand on valide

Sinon,

![WhatsApp Image 2023-07-29 à 20 49 57](https://github.com/AntoninLoubiere/hanamikoji-site/assets/61625831/cc55213c-7161-4193-a832-d8acafbdeef7)

Là on ajoute un par un mais la vérification est simple. Seule difficulté, il faut enlever de la liste les champions qui sont déjà sélectionnés. 


Par contre, je pense que le plus simple c'est quand même de faire la sélection directement sur la page détail du tournoi pour prévoir à l'avance les champions que vont le mettre, au lieu de s'embrouiller à savoir lequel est le prochain. Bien-sûr, on enlève pas le gros bouton "Voir le prochain tournoi".
Je dis ça parce que par exemple si on veut insérer un tournoi (avant celui qui serait le prochain), c'est mieux si l'on est toujours de la visibilité sur le tournoi où on a choisi nos champions

**Comment by AntoninLoubiere** [comment]
Je pense que la première interface est plus simple si on le fait par tournoi, on pourra limiter avec du JS le nombre de champions qui participent sélectionnés et lors du lancement du tournois compléter au besoin s'il y en a pas assez ?

Je pense que dans ce cas on peut enlever le bouton prochain tournoi et le remplacer avec une section qui résume le prochain tournoi et qui affiche si l'utilisateur a choisi ou non ses champions (avec un gros compte à rebours de la mort qui tue ?)
