### ISSUE TITLE
Page /tournois/<id>

### ISSUE THREAD

**Issue by AntoninLoubiere** [AntoninLoubiere/hanamikoji-site#32]
Informations sur un tournois : date de lancement, statut (cf #30)
Il faut ajouter un attribut tournois sur les matchs pour identifier les matchs qui font partie d'un tournois.
Il faut ajouter un attribut ManyToMany entre les champions et les tournois pour enregistrer les scores : nombre de matchs gagnés et nombre de points.

Si en cours afficher le nombre de matchs terminé sur le nombre de match à faire ?

liste des champions / classement des champions :
Sur chaque ligne afficher le nom du champion, le nombre de matchs gagnés et le nombre de points obtenus (si le tournois est fini)

Classement : nombre de victoires puis si égalité nombre de points

Sur une autre page / en bas
Tableau des matchs jouées (chaque champion rencontre chaque autre champion deux fois, en tant que joueur 1 puis en tant que joueur 2).

Chaque ligne / chaque colonne est un champion
Sur chaque case un lien vers le match /match/<id> entre le joueur de la ligne est le joueur de la colonne, avec le texte Score joueur 1 vs Score Joueur 2, la couleur de la case dépends si le joueur 1 a gagné (Vert - Orange - Rouge ?). Les joueurs 1 sont sur les lignes, les joueurs 2 sur les colonnes.

Si l'utilisateur possèdent la permission tournois.create ajouter un bouton programmer le lancement / annuler le lancement.
Permettre de modifier la date et l'heure du lancement ?

**Comment by Triw-12** [comment]
Classement : Uniquement le nombre de points, sous la forme 3 si victoire 1 si égalité 0 si perdu
Même classement si même nombre de points

**Comment by Triw-12** [comment]
Je n'arrive pas à faire le tableau à deux entrées qui récapitule les matchs...  Je te laisse le faire (la difficulté c'est que on a tous les matchs d'un coup et il faut faire une distinction lorsque l'on change de premier champion). Si tu m'explique comment je peux faire, je le fait

PS : Je vais quand même faire le choix des champions
