### ISSUE TITLE
Faire des tournois avec plus de matchs

### ISSUE THREAD

**Issue by AntoninLoubiere** [AntoninLoubiere/hanamikoji-site#48]
Étant donné qu'il y a une partie d'aléatoire avec la distribution des cartes, ça serait bien si on pouvait faire des tournois où chaque joueur se rencontre 2x fois

**Comment by Triw-12** [comment]
Où est l'endroit où tu lances les matchs ?

**Comment by Triw-12** [comment]
Je propose pour l'affichage graphique de mettre pour chaque cellule les différents score séparé par un retour à la ligne. 
Donc on laisse tomber pour la couleur de la cellule en vert/rouge mais on met plutôt chaque score en vert/rouge (en fonction de quel joueur gagne)
Par simplicité, je propose que l'on puisse faire que un nombre de match pair
