### ISSUE TITLE
Play as user

### ISSUE THREAD

**Issue by D4sny** [AntoninLoubiere/hanamikoji-site#81]
Impossible to play against a bot as a human player

**Comment by Triw-12** [comment]
Beaucoup de boulot.... @AntoninLoubiere , essaie de penser pour faire en sorte que ce soit aussi possible que l'on puisse jouer en un contre un (sans bot) avant que l'on ne nous demande cette fonctionnalité et pour éviter de faire sensiblement la même chose 2 fois
