### ISSUE TITLE
Le replay ne se met pas à jour dans play !

### ISSUE THREAD

**Issue by Triw-12** [AntoninLoubiere/hanamikoji-site#91]

**Comment by AntoninLoubiere** [comment]
Il semblerait que le replay se met bien à jour quand on joue à deux. Je laisse cet issue ouverte, si cela se reproduit il faudrait donner la date du problème et le nom de l'adversaire.

**Comment by Triw-12** [comment]
Match : moi contre Termikoji-2000beta
Premier joueur : Au hasard mais il me semble que c'est lui qui a commencé
Statut : Terminé sur une égalité au bout de 3 manches 
Date : Il y a quelques minutes...
**Replay : Non mis à jour (toujours le dernier match Tristan-Antonin)**

**Comment by Triw-12** [comment]
Problème : C'est toujours Termikoji-2000beta qui commence en premier, même si je choisis "Vous jouez en premier"

**Comment by AntoninLoubiere** [comment]
Problème de cache ?

**Comment by Triw-12** [comment]
C'est bien un problème de cache

**Comment by Triw-12** [comment]
Il y a un moyen de recharger le cache à chaque fois mais de préférence uniquement les éléments que l'on sait que l'on veut recharger (le fichier dump) ou au pire seulement la page play (parce que le reste on veut que le cache reste) ?

**Comment by AntoninLoubiere** [comment]
Normalement j'ai rajouté l'entête [Cache-Cotnrol: no-cache](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#no-cache) sur l'URL `/media/play/*`. Tu peux vérifier que ça marche bien ?
